### ISSUE TITLE
PersistentPreRunE of command will override the custom PersistentPreRunE of the root command

### ISSUE THREAD

**Issue by hyorigo** [carolynvs/stingoftheviper#1]
Hi there,
I tried your solution that use the custom PersistentPreRunE to handle envvar, but after I set PersistentPreRunE of the non-root command and I found that the magic is gone, the very custom PersistentPreRunE of root is not executed.

**Comment by carolynvs** [comment]
Using the root command's PersistentPreRunE as a universal hook was an example of one place you may find convenient to call the setup code. If that doesn't work for you (sounds like it doesn't), then you will need to find a hook that works for your codebase. Everyone is different so I cannot help with that, sorry.

The important part is to call `initializeConfig` before your run your command, how you accomplish it doesn't really matter. I hope that helps!
