### ISSUE TITLE
Needing BindPFlags as well?

### ISSUE THREAD

**Issue by lukemarsden** [carolynvs/stingoftheviper#2]
Hi there, thanks for your blog post and this code repo! I was facing exactly the same problem and it helped me solve it.

I found it was necessary to also run ([ref](https://github.com/spf13/viper#working-with-flags)):
```
viper.BindPFlags(cmd.Flags())
```
In order to get the values out from `viper.Get` and friends. Might be worth adding a note to this effect to `initializeConfig` in the code and the blog post?

My working initializeConfig ended up looking like:
```
	AppConfig = viper.New()
	AppConfig.SetEnvPrefix(envPrefix)
	AppConfig.AutomaticEnv()
	AppConfig.BindPFlags(cmd.Flags())
	bindFlags(cmd, AppConfig)
```
Using your `bindFlags` function as-is. Again, thank you! 🙏

**Comment by lukemarsden** [comment]
And in fact, if I add a `SetEnvKeyReplacer`, then as long as I access the values via `viper.Get`, I don't need to call `bindFlags` at all:
```
	AppConfig = viper.New()
	AppConfig.SetEnvPrefix(envPrefix)
	AppConfig.AutomaticEnv()
	AppConfig.BindPFlags(cmd.Flags())
	replacer := strings.NewReplacer("-", "_")
	AppConfig.SetEnvKeyReplacer(replacer)
```
Possibly an overall simpler solution?

**Comment by carolynvs** [comment]
I was trying to solve a slightly different problem actually. I don't want to use viper throughout the rest of my code, and I limit that dependency to just the cmd package. I wanted to bind the config file, env vars and flags to a data structure and then use that struct throughout my code.

I'm glad that you found something that worked for you though!
