### ISSUE TITLE
Not working when parameters contains a dash and loading from configfiles

### ISSUE THREAD

**Issue by trunet** [carolynvs/stingoftheviper#3]
First of all, thank you very much for putting all of it together. It's really helpful.

My const:
```golang
const (
	defaultConfigFilename = "MYAPP"
	envPrefix             = "MYAPP"
)
```

My config flags have a dash, per example:
`rootCmd.Flags().StringVarP(&influxdb_url, "influxdb-url", "r", "", "InfluxDB URL")`

I'm using inside docker stack, therefore I would like to supply with a environment file. I created a secret called MYAPP.env that is loaded from /run/secrets, and added:
`v.AddConfigPath("/run/secrets")`

Inside this file, it contains:
`MYAPP_INFLUXDB_URL=http://influxdb.my.domain:8086`

I manage to fix it doing:
````golang
func bindFlags(cmd *cobra.Command, v *viper.Viper) {
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		envVarSuffix := strings.ToUpper(strings.ReplaceAll(f.Name, "-", "_"))
		varName := fmt.Sprintf("%s_%s", envPrefix, envVarSuffix)
		if strings.Contains(f.Name, "-") {
			v.BindEnv(f.Name, varName)
		}

		if !f.Changed && v.IsSet(varName) {
			val := v.Get(varName)
			cmd.Flags().Set(f.Name, fmt.Sprintf("%v", val))
		}
	})
}
```

**Comment by ezk84** [comment]
This should also be fixed by #5

**Comment by carolynvs** [comment]
@trunet What does your configuration file look like? Sounds like you are using hyphens in the flag name but want to use underscores in the config file?

For example, in the config file, if you have a flag named log-level, is it "logLevel", "log-level" or "log_level" in the config file?

**Comment by trunet** [comment]
dash is not supported in environment variables, therefore the way to support is to "convert" - to _

**Comment by carolynvs** [comment]
Yup, I do understand that. I thought you were having problems with your config file, not environment variables. Since the example has had some improvements since you posted so I'm going to close this since it does support changing flags with dashes to underscores when binding to environment variables. 👍
